config/routes.rb
Rails.application.routes.draw do
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |task| %> <%= task.label :title %>
<%= task.text_field :title %><br>
<%= task.label :details %>
<%= task.text_field :details %><br>
<%= task.label :completed %>
<%= task.check_box :completed %><br>
<%= task.submit %> <% end %>

app/views/tasks/edit.html.erb
<h1>Edit my task</h1>
<%= render 'form', task: @task %>
<%= link_to "View all my tasks", tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>
  <div>
    <% if task.completed %>
    <i class="fas fa-check-square"></i>
     <strong><%= link_to task["title"], task_path(task.id) %></strong><br>
    <%= task.details %>
    <% else %>
    <i class="far fa-square"></i>
    <strong><%= link_to task["title"], task_path(task.id) %></strong><br>
    <%= task.details %>
    <% end %>
    <%= link_to "delete a task", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %><h3>
  </div>
  <br>
<% end %>
  <hr>
<br>
<%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>
<%= render 'form', task: @task %>
<%= link_to "View all my tasks", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<%= link_to "Edit this task", edit_path %>
<%= link_to "View all my tasks", tasks_path %>

app/views/tasks/tasks.html.erb
<h1>My tasks</h1>
<p><%= params[:task] %></p>
<p><%= @result %></p>